/**
 * 화면 UI 문구 상수.
 * 에러 메시지는 백엔드 messages.ts 에서 관리하며 프론트는 그대로 표시한다.
 * 이 파일에는 레이블·플레이스홀더·버튼 텍스트 등 화면 구성 문구만 정의한다.
 */
export const strings = {
  /** 에러 표시용 공통 — Alert 타이틀, 서버 응답 없을 때 폴백 */
  common: {
    errorTitle:       '오류',
    errorFallback:    '오류가 발생했습니다.',
    logoutConfirmTitle: '로그아웃',
    logoutConfirmMsg:   '로그아웃 하시겠습니까?',
    confirm:            '확인',
    cancel:             '취소',
  },

  splash: {
    logo:  'P',
    title: 'Pingo',
  },

  login: {
    title:        '로그인',
    email:        '이메일',
    password:     '비밀번호',
    saveEmail:    '이메일 저장',
    autoLogin:    '자동 로그인',
    submit:       '로그인',
    noAccount:    '계정이 없으신가요? 승인 요청',
    /** 유효성 오류·잘못된 자격증명 — 상세 내용 노출 없이 통합 안내 */
    invalidInput: '이메일 또는 비밀번호를 확인해주세요.',
  },

  approvalRequest: {
    title:    '승인 요청',
    desc:     '관리자 승인 후 사용 가능합니다.',
    email:    '이메일',
    password: '비밀번호',
    submit:   '신청',
  },

  approvalPending: {
    title: '승인 대기 중',
    desc:  '관리자가 계정을 검토 중입니다.\n승인 후 이용 가능합니다.',
    back:  '로그인으로 돌아가기',
  },

  rejectedAccount: {
    title: '승인이 거절되었습니다',
    desc:  '계정 사용이 거절되었습니다.\n자세한 문의는 관리자에게 연락해주세요.',
    back:  '로그인으로 돌아가기',
  },

  deviceChange: {
    title:  '기기가 변경되었습니다',
    desc:   '현재 기기는 관리자 승인이 필요합니다.\n기존 기기는 정상적으로 사용 가능합니다.',
    submit: '승인 요청하기',
  },

  home: {
    headerFmt:          (month: number) => `${month}월 소비 현황`,
    totalLabel:         '이번달 총 소비',
    vsMoreFmt:          (n: number) => `지난달보다 ${n.toLocaleString()}원 더 씀`,
    vsLessFmt:          (n: number) => `지난달보다 ${n.toLocaleString()}원 덜 씀`,
    vsSame:             '지난달과 동일',
    noLastMonth:        '지난달 데이터 없음',
    categoryTopTitle:   '카테고리별 소비',
    categoryOthersFmt:  (n: number) => `기타 ${n}개`,
    toStats:            '통계에서 더 보기 ›',
    budgetAlertTitle:   '예산 알림',
    budgetNearFmt:      (name: string, pct: number) => `${name} ${pct}% 도달`,
    budgetOverFmt:      (name: string) => `${name} 예산 초과`,
    recentTitle:        '최근 거래내역',
    toHistory:          '전체 보기 ›',
    trendTitle:         '소비 추이',
    trendMonthFmt:      (m: number) => `${m}월`,
    noData:             '이번달 거래 내역이 없습니다.',
    noCategory:         '기타',
  },

  more: {
    header:          '전체',
    fixedExpenses:   '고정 지출 관리',
    paymentMethods:  '결제수단 관리',
    myInfo:          '내 정보',
  },

  paymentMethods: {
    header:              '결제수단 관리',
    noCards:             '등록된 카드 정보가 없습니다.',
    addCard:             '등록하기',
    headerCreate:        '카드 등록',
    headerEdit:          '카드 수정',
    nameLabel:           '카드사',
    namePlaceholder:     '예: 신한, 국민',
    cardNumberLabel:     '카드번호',
    cardNumberSuffix:    '끝 4자리',
    cardNumberPlaceholder: '카드번호 입력 (선택)',
    submit:              '등록하기',
    update:              '수정하기',
    deleteBtn:           '카드 삭제',
    deleteConfirmTitle:  '카드 삭제',
    deleteConfirmMsg:    '이 카드를 삭제하시겠습니까?',
    errNameEmpty:        '카드사를 입력해주세요.',
    successCreate:       '카드가 등록됐습니다.',
    successUpdate:       '카드가 수정됐습니다.',
    successDelete:       '카드가 삭제됐습니다.',
  },

  myInfo: {
    header:                  '내 정보',
    emailLabel:              '이메일',
    changePassword:          '비밀번호 변경',
    logout:                  '로그아웃',
    devicesHeader:           '내 기기',
    currentDeviceBadge:      '현재 기기',
    deleteDevice:            '삭제',
    confirmDeleteOtherTitle: '기기 삭제',
    confirmDeleteOtherMsg:   '삭제하면 해당 기기에서 다시 로그인 시 승인 요청이 필요합니다. 계속하시겠습니까?',
    confirmDeleteCurrentTitle: '현재 기기 삭제',
    confirmDeleteCurrentMsg:   '삭제하면 승인 요청이 필요하고 로그아웃 처리됩니다. 계속하시겠습니까?',
  },

  passwordChange: {
    header:          '비밀번호 변경',
    currentPassword: '현재 비밀번호',
    newPassword:     '새 비밀번호',
    confirmPassword: '새 비밀번호 확인',
    submit:          '변경',
    errCurrentEmpty: '현재 비밀번호를 입력해주세요.',
    errNextEmpty:    '새 비밀번호를 입력해주세요.',
    errNextShort:    '비밀번호는 8자 이상이어야 합니다.',
    errConfirmEmpty: '비밀번호 확인을 입력해주세요.',
    errConfirmMismatch: '새 비밀번호가 일치하지 않습니다.',
  },

  adminTabs: {
    userManagement:     '유저 관리',
    approvalManagement: '승인 관리',
    more:               '전체',
  },

  adminMore: {
    header: '전체',
    logout: '로그아웃',
  },

  approvalManagement: {
    header:          '승인 관리',
    totalCount:      (n: number) => `총 ${n}건`,
    tabPending:      '대기',
    tabRejected:     '거절',
    emptyPending:    '대기 중인 승인 요청이 없습니다.',
    emptyRejected:   '거절된 승인 요청이 없습니다.',
    badgeNewUser:    '신규',
    badgeNewDevice:  '기기 추가',
    approve:         '승인',
    reject:          '거절',
    accept:          '수락',
    delete:          '삭제',
    confirmAccept: {
      title:   '수락 확인',
      message: '거절된 요청을 수락하시겠습니까?',
      ok:      '수락',
      cancel:  '취소',
    },
    confirmDelete: {
      title:   '삭제 확인',
      message: '삭제하시겠습니까?',
      ok:      '삭제',
      cancel:  '취소',
    },
  },

  category: {
    header:         '카테고리',
    empty:          '카테고리가 없습니다.',
    statCountLabel: '카테고리',
    statBudgetLabel:'총 예산',
    countFmt:       (n: number) => `${n}개`,
    budgetFmt:      (n: number) => `${n.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')}원`,
    noBudget:       '예산 없음',
    sortBudget: '예산',
    sortName:   '이름',
    sortDate:   '등록일',
  },

  categoryEdit: {
    headerCreate:     '카테고리 등록',
    headerEdit:       '카테고리 수정',
    iconLabel:        '아이콘',
    colorLabel:       '색상',
    nameLabel:        '카테고리명',
    namePlaceholder:  '예: 식비, 교통비',
    budgetLabel:      '이번 달 예산',
    budgetPlaceholder: '미입력 시 예산 없음',
    budgetUnit:       '원',
    fixedBudget:      '매달 예산 고정',
    fixedBudgetDesc:  '매달 동일한 예산을 자동 적용합니다.',
    budgetHint:       '예산을 설정하면 차트에서 카테고리별 사용 현황을 확인할 수 있습니다.',
    submit:           '등록하기',
    update:           '수정하기',
    successCreate:    '카테고리가 등록됐습니다.',
    successUpdate:    '카테고리가 수정됐습니다.',
    successDelete:    '카테고리가 삭제됐습니다.',
    deleteBtn:        '카테고리 삭제',
    deleteTitle:      '카테고리 삭제',
    deleteMessage:    '이 카테고리에 속한 내역들을 이동할 카테고리를 선택해주세요.',
    deleteNoCategory: '선택안함 (기타)',
    deleteConfirm:    '삭제',
    errNameEmpty:     '카테고리명을 입력해주세요.',
    colorPickerTitle: '색상 선택',
    colorPickerConfirm: '선택',
    emojiPickerTitle: '아이콘 선택',
  },

  transactionEdit: {
    headerCreate:        '내역 추가',
    headerEdit:          '내역 수정',
    amountLabel:         '금액',
    amountPlaceholder:   '0',
    merchantLabel:       '가맹점',
    merchantPlaceholder: '가맹점명 입력',
    categoryLabel:       '카테고리',
    noCategoryLabel:     '기타 (미분류)',
    categoryPickerEmpty: '카테고리가 없습니다.',
    categoryPickerTitle: '카테고리 선택',
    paymentMethodLabel:        '결제수단',
    paymentMethodPlaceholder:  '결제수단 선택 (선택)',
    paymentMethodPickerTitle:  '결제수단 선택',
    paymentMethodPickerEmpty:  '등록된 결제수단이 없습니다.',
    paymentMethodSectionFixed: '기본',
    paymentMethodSectionCard:  '카드',
    memoLabel:           '메모',
    memoPlaceholder:     '메모 입력 (선택)',
    dateLabel:           '날짜',
    timeLabel:           '시간',
    submit:              '등록하기',
    update:              '수정하기',
    deleteBtn:           '내역 삭제',
    deleteConfirmTitle:  '내역 삭제',
    deleteConfirmMsg:    '이 내역을 삭제하시겠습니까?',
    successCreate:       '내역이 등록됐습니다.',
    successUpdate:       '내역이 수정됐습니다.',
    successDelete:       '내역이 삭제됐습니다.',
    errAmountEmpty:      '금액을 입력해주세요.',
    errMerchantEmpty:    '가맹점명을 입력해주세요.',
  },

  timePicker: {
    title:  '시간 선택',
    hour:   '시',
    minute: '분',
    format: (h: number, m: number) => `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`,
  },

  datePicker: {
    weekdays:    ['일', '월', '화', '수', '목', '금', '토'],
    months:      ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    monthFormat:      (year: number, month: number) => `${year}년 ${month}월`,
    yearFormat:       (year: number) => `${year}년`,
    dateFormat:       (year: number, month: number, day: number) => `${year}년 ${month}월 ${day}일`,
    dateWithDowFormat: (year: number, month: number, day: number, dow: string) => `${year}년 ${month}월 ${day}일 (${dow})`,
  },

  history: {
    header:      '내역',
    empty:       '내역이 없습니다.',
    tabDay:      '일',
    tabMonth:    '월',
    tabYear:     '년',
    today:       '오늘',
    dateFormat:  (y: number, m: number, d: number) => `${y}년 ${m}월 ${d}일`,
    totalAmount: (n: number) => `총 ${n.toLocaleString()}원`,
    noCategory:  '기타',
    groupHourFmt:  (hour: number) => `${hour}시`,
    groupDayFmt:   (day: number, dow: string) => `${day}일 (${dow})`,
    groupMonthFmt: (month: number) => `${month}월`,
  },

  stats: {
    header:      '통계',
    placeholder: (tab: string) => `${tab} 통계 준비 중`,
    tabDay:      '일',
    tabMonth:    '월',
    tabYear:     '년',
  },

  fixedExpenses: {
    header:          '고정 지출 관리',
    empty:           '등록된 고정 지출이 없습니다.',
    tabList:         '리스트',
    tabCalendar:     '달력',
    dayOfMonthFmt:   (d: number) => `매월 ${d}일`,
    activeLabel:     '자동 등록 중',
    inactiveLabel:   '자동 등록 꺼짐',
  },

  fixedExpenseEdit: {
    headerCreate:           '고정 지출 추가',
    headerEdit:             '고정 지출 수정',
    merchantNameLabel:      '가맹점명',
    merchantNamePlaceholder:'가맹점명 입력',
    amountLabel:            '금액',
    amountPlaceholder:      '금액 입력',
    categoryLabel:          '카테고리',
    categoryPlaceholder:    '카테고리 선택',
    paymentMethodLabel:     '결제수단',
    paymentMethodPlaceholder:'결제수단 선택 (선택)',
    memoLabel:              '메모',
    memoPlaceholder:        '메모 입력 (선택)',
    dayOfMonthLabel:        '매월 지출일',
    dayOfMonthPlaceholder:  '1 ~ 31',
    isActiveLabel:          '매월 자동 등록',
    confirmDisableTitle:    '자동 등록 끄기',
    confirmDisableMsg:      '자동 등록을 끄면 매월 자동으로 내역이 추가되지 않습니다. 계속하시겠습니까?',
    confirmDisableOk:       '끄기',
    confirmDisableCancel:   '취소',
    saveButton:             '저장',
    deleteButton:           '삭제',
    confirmDeleteTitle:     '고정 지출 삭제',
    confirmDeleteMsg:       '삭제하면 복구할 수 없습니다. 삭제하시겠습니까?',
    confirmDeleteOk:        '삭제',
    errMerchantEmpty:       '가맹점명을 입력해 주세요.',
    errAmountEmpty:         '금액을 입력해 주세요.',
    errDayEmpty:            '1~31 사이의 날짜를 입력해 주세요.',
    successCreate:          '고정 지출이 등록되었습니다.',
    successUpdate:          '저장되었습니다.',
  },

  userManagement: {
    header:      '유저 관리',
    searchPlaceholder: '이메일 검색',
    totalCount:  (n: number) => `총 ${n}명`,
    tabActive:   '활성',
    tabSuspended: '정지',
    empty:       '유저가 없습니다.',
    emptySearch: '검색 결과가 없습니다.',
    deviceLabel: (n: number) => `기기 ${n}`,
    suspend:     '사용 정지',
    unsuspend:   '정지 해제',
    confirmSuspendTitle:   '사용 정지',
    confirmSuspendMsg:     '해당 유저를 사용 정지하면 즉시 강제 로그아웃 처리됩니다. 계속하시겠습니까?',
    confirmUnsuspendTitle: '정지 해제',
    confirmUnsuspendMsg:   '해당 유저의 정지를 해제하시겠습니까?',
  },

  userTabs: {
    home:     '홈',
    history:  '내역',
    stats:    '통계',
    category: '카테고리',
    more:     '전체',
  },
} as const
