/**
 * 화면 UI 문구 상수.
 * 에러 메시지는 백엔드 messages.ts 에서 관리하며 프론트는 그대로 표시한다.
 * 이 파일에는 레이블·플레이스홀더·버튼 텍스트 등 화면 구성 문구만 정의한다.
 */
export const strings = {
  /** 에러 표시용 공통 — Alert 타이틀, 서버 응답 없을 때 폴백 */
  common: {
    errorTitle:       '오류',
    errorFallback:    '오류가 발생했습니다.',
    logoutConfirmTitle: '로그아웃',
    logoutConfirmMsg:   '로그아웃 하시겠습니까?',
    confirm:            '확인',
    cancel:             '취소',
  },

  splash: {
    logo:  'P',
    title: 'Pingo',
  },

  login: {
    title:        '로그인',
    email:        '이메일',
    password:     '비밀번호',
    saveEmail:    '이메일 저장',
    autoLogin:    '자동 로그인',
    submit:       '로그인',
    noAccount:    '계정이 없으신가요? 승인 요청',
    /** 유효성 오류·잘못된 자격증명 — 상세 내용 노출 없이 통합 안내 */
    invalidInput: '이메일 또는 비밀번호를 확인해주세요.',
  },

  approvalRequest: {
    title:    '승인 요청',
    desc:     '관리자 승인 후 사용 가능합니다.',
    email:    '이메일',
    password: '비밀번호',
    submit:   '신청',
  },

  approvalPending: {
    title: '승인 대기 중',
    desc:  '관리자가 계정을 검토 중입니다.\n승인 후 이용 가능합니다.',
    back:  '로그인으로 돌아가기',
  },

  rejectedAccount: {
    title: '승인이 거절되었습니다',
    desc:  '계정 사용이 거절되었습니다.\n자세한 문의는 관리자에게 연락해주세요.',
    back:  '로그인으로 돌아가기',
  },

  deviceChange: {
    title:  '기기가 변경되었습니다',
    desc:   '현재 기기는 관리자 승인이 필요합니다.\n기존 기기는 정상적으로 사용 가능합니다.',
    submit: '승인 요청하기',
  },

  home: {
    headerFmt:          (month: number) => `${month}월 소비 현황`,
    totalLabel:         '이번달 총 소비',
    vsMoreFmt:          (n: number) => `지난달보다 ${n.toLocaleString()}원 더 씀`,
    vsLessFmt:          (n: number) => `지난달보다 ${n.toLocaleString()}원 덜 씀`,
    vsSame:             '지난달과 동일',
    noLastMonth:        '지난달 데이터 없음',
    categoryTopTitle:   '카테고리별 소비',
    categoryOthersFmt:  (n: number) => `기타 ${n}개`,
    toStats:            '통계에서 더 보기 ›',
    budgetAlertTitle:   '예산 알림',
    budgetNearFmt:      (name: string, pct: number) => `${name} ${pct}% 도달`,
    budgetOverFmt:          (name: string) => `${name} 예산 초과`,
    budgetOverDetailFmt:    (budget: number, over: number) => `예산 ${budget.toLocaleString()}원 · +${over.toLocaleString()}원 초과`,
    budgetPctFmt:           (pct: number) => `예산 ${pct}%`,
    recentTitle:        '최근 거래내역',
    toHistory:          '전체 보기 ›',
    trendTitle:         '소비 추이',
    trendMonthFmt:      (m: number) => `${m}월`,
    noData:             '이번달 거래 내역이 없습니다.',
    noCategory:         '기타',
  },

  more: {
    header:                '전체',
    fixedExpenses:         '고정 지출 관리',
    paymentMethods:        '결제수단 관리',
    myInfo:                '내 정보',
    pendingNotifications:  '미등록 알림',
  },

  pendingNotifications: {
    header:              '미등록 알림',
    empty:               '미등록 결제 알림이 없습니다.',
    expiryNotice:        '받은 알림은 1주일 후 자동으로 삭제됩니다.',
    registerBtn:         '등록',
    bulkRegisterBtn:     '일괄 등록',
    oldBadge:            '3일+',
    unparseable:         '파싱 불가',

    nextConfirmTitle:    '다음 내역 등록',
    nextConfirmMsg:      '다음 미등록 내역도 등록하시겠습니까?',
    nextConfirmOk:       '등록',
    nextConfirmCancel:   '나중에',

    bulkConfirmTitle:    '일괄 등록',
    bulkCategoryNotice:  '카테고리: 기타(미분류)로 등록됩니다.',
    bulkConfirmMsg:      (n: number) => `총 ${n}건을 등록합니다.`,
    bulkConfirmOk:       '등록',
    bulkConfirmCancel:   '취소',
    bulkSuccessMsg:      (n: number) => `${n}건이 등록됐습니다.`,
    bulkPartialMsg:      (ok: number, fail: number) => `${ok}건 등록 완료, ${fail}건 실패`,
    bulkNothingTitle:    '알림',
    bulkNothingMsg:      '등록 가능한 내역이 없습니다.',
    lumpSum:             '일시불',
    installmentFmt:      (n: number) => `${n}개월 할부`,
    installmentUnknown:  '할부',

    card: {
      issuer:   '카드사',
      amount:   '사용금액',
      payType:  '결제유형',
      date:     '날짜',
      time:     '시간',
      merchant: '가맹점명',
    },
  },

  notification: {
    channelName:         'Pingo 알림',
    detectedTitle:       '새 결제 알림이 왔어요',
    detectedBodyFmt:     (app: string, text: string) => `${app}\n${text}\n탭하면 지출 내역으로 바로 등록할 수 있어요.`,
    reminderTitle:       '아직 등록하지 않은 결제가 있어요',
    reminderBody:        '받은 결제 알림이 아직 가계부에 등록되지 않았어요. 탭해서 지금 바로 기록해보세요.',
  },

  cancelledTransactionSearch: {
    header:              '원 거래 내역 찾기',
    cancelInfoTitle:     '취소 알림 내역',
    sectionDb:           '등록된 내역',
    sectionPending:      '미등록 알림',
    notFound:            '원 거래 내역을 찾지 못했습니다.',
    notFoundHint:        '가맹점명·금액·결제유형이 일치하는 내역이 없습니다.',
    merchant:            '가맹점',
    amount:              '취소 금액',
    payType:             '결제유형',
    issuer:              '카드사',
    date:                '취소 일시',
    lumpSum:             '일시불',
    installmentFmt:      (n: number) => `${n}개월 할부`,
    installmentUnknown:  '할부',
    removePendingTitle:  '미등록 알림 삭제',
    removePendingMsg:    '승인 직후 취소된 것으로 보입니다. 미등록 알림을 삭제하시겠습니까?',
    removePendingOk:     '삭제',
    notification: {
      detectedTitle:    '결제 취소 알림이 왔어요',
      detectedBodyFmt:  (app: string, text: string) => `${app}\n${text}\n탭하면 원 거래 내역을 찾을 수 있어요.`,
    },
  },

  permission: {
    notificationListenerTitle: '알림 접근 권한 필요',
    notificationListenerMsg:   'Pingo가 카드 결제 알림을 읽으려면 알림 접근 권한이 필요합니다.\n\n설정 화면에서 Pingo를 허용해주세요.',
    later:                     '나중에',
    goToSettings:              '설정으로 이동',
    batteryOptTitle:           '배터리 최적화 설정',
    batteryOptMsg:             '앱이 완전히 종료된 상태에서도 알림을 읽으려면 배터리 최적화를 꺼야 합니다.\n\n설정 > 애플리케이션 > Pingo > 배터리 > 제한 없음으로 설정해주세요.',
  },

  paymentMethods: {
    header:              '결제수단 관리',
    noCards:             '등록된 카드 정보가 없습니다.',
    addCard:             '등록하기',
    addPaymentMethod:    '+ 결제수단 추가',
    headerCreate:        '카드 등록',
    headerEdit:          '카드 수정',
    nameLabel:           '카드사',
    namePlaceholder:     '예: 신한, 국민',
    cardNumberLabel:     '카드번호',
    cardNumberSuffix:    '끝 4자리',
    cardNumberPlaceholder: '카드번호 입력 (선택)',
    submit:              '등록하기',
    update:              '수정하기',
    deleteBtn:           '카드 삭제',
    deleteConfirmTitle:  '카드 삭제',
    deleteConfirmMsg:    '이 카드를 삭제하시겠습니까?',
    errNameEmpty:               '카드사를 입력해주세요.',
    successCreate:              '카드가 등록됐습니다.',
    successUpdate:              '카드가 수정됐습니다.',
    successDelete:              '카드가 삭제됐습니다.',
    isDefaultLabel:             '기본 결제수단으로 설정',
    changeDefaultConfirmTitle:  '기본 결제수단 변경',
    changeDefaultConfirmMsg:    (prevName: string) => `기존 기본 결제수단 "${prevName}"이 해제됩니다. 변경하시겠습니까?`,
  },

  myInfo: {
    header:                  '내 정보',
    emailLabel:              '이메일',
    changePassword:          '비밀번호 변경',
    darkMode:                '다크 모드',
    logout:                  '로그아웃',
    devicesHeader:           '내 기기',
    currentDeviceBadge:      '현재 기기',
    deleteDevice:            '삭제',
    confirmDeleteOtherTitle: '기기 삭제',
    confirmDeleteOtherMsg:   '삭제하면 해당 기기에서 다시 로그인 시 승인 요청이 필요합니다. 계속하시겠습니까?',
    confirmDeleteCurrentTitle: '현재 기기 삭제',
    confirmDeleteCurrentMsg:   '삭제하면 승인 요청이 필요하고 로그아웃 처리됩니다. 계속하시겠습니까?',
  },

  passwordChange: {
    header:          '비밀번호 변경',
    currentPassword: '현재 비밀번호',
    newPassword:     '새 비밀번호',
    confirmPassword: '새 비밀번호 확인',
    submit:          '변경',
    errCurrentEmpty: '현재 비밀번호를 입력해주세요.',
    errNextEmpty:    '새 비밀번호를 입력해주세요.',
    errNextShort:    '비밀번호는 8자 이상이어야 합니다.',
    errConfirmEmpty: '비밀번호 확인을 입력해주세요.',
    errConfirmMismatch: '새 비밀번호가 일치하지 않습니다.',
  },

  adminTabs: {
    userManagement:     '유저 관리',
    approvalManagement: '승인 관리',
    more:               '전체',
  },

  adminMore: {
    header:              '전체',
    schedulerManagement: '스케줄러 관리',
    logout:              '로그아웃',
  },

  schedulerManagement: {
    header:              '스케줄러 관리',
    runBtn:              '이번 달 스케줄러 일괄 실행',
    runConfirm:          '이번 달 스케줄러 3종을 모두 수동으로 실행하시겠습니까?',
    runByTypeBtn:        '수동 실행',
    runByTypeConfirm:    (type: string) => `${type} 스케줄러를 수동으로 실행하시겠습니까?`,
    statusSectionTitle:  (year: number, month: number) => `${year}년 ${month}월 실행 현황`,
    types: {
      BUDGET_ROLLOVER: '예산 이월',
      FIXED_EXPENSES:  '고정 지출',
      INSTALLMENTS:    '할부 납입',
    },
    triggers: {
      CRON:   '자동',
      MANUAL: '수동',
    },
    tabs: {
      all:     '전체',
      success: '성공',
      failure: '실패',
      notRun:  '미실행',
    },
    statusCard: {
      success: '성공',
      failure: '실패',
      notRun:  '미실행',
    },
    detail: {
      type:         '스케줄러',
      yearMonth:    '실행 월',
      runAt:        '실행 시각',
      trigger:      '실행 방식',
      status:       '결과',
      totalCount:   '대상 건수',
      successCount: '생성 건수',
      error:        '오류 내용',
    },
    empty:      '실행 기록이 없습니다.',
    runSuccess: '스케줄러 실행이 완료됐습니다.',
  },

  approvalManagement: {
    header:          '승인 관리',
    totalCount:      (n: number) => `총 ${n}건`,
    tabPending:      '대기',
    tabRejected:     '거절',
    emptyPending:    '대기 중인 승인 요청이 없습니다.',
    emptyRejected:   '거절된 승인 요청이 없습니다.',
    badgeNewUser:    '신규',
    badgeNewDevice:  '기기 추가',
    approve:         '승인',
    reject:          '거절',
    accept:          '수락',
    delete:          '삭제',
    confirmAccept: {
      title:   '수락 확인',
      message: '거절된 요청을 수락하시겠습니까?',
      ok:      '수락',
      cancel:  '취소',
    },
    confirmDelete: {
      title:   '삭제 확인',
      message: '삭제하시겠습니까?',
      ok:      '삭제',
      cancel:  '취소',
    },
  },

  category: {
    header:         '카테고리',
    empty:          '카테고리가 없습니다.',
    statCountLabel: '카테고리',
    statBudgetLabel:'총 예산',
    countFmt:       (n: number) => `${n}개`,
    budgetFmt:      (n: number) => `${n.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')}원`,
    noBudget:       '예산 없음',
    sortBudget:     '예산',
    sortName:       '이름',
    sortDate:       '등록일',
    limitReached:   '카테고리는 최대 20개까지 등록할 수 있습니다.',
  },

  categoryEdit: {
    headerCreate:     '카테고리 등록',
    headerEdit:       '카테고리 수정',
    iconLabel:        '아이콘',
    colorLabel:       '색상',
    nameLabel:        '카테고리명',
    namePlaceholder:  '예: 식비, 교통비',
    budgetLabel:      '이번 달 예산',
    budgetPlaceholder: '미입력 시 예산 없음',
    budgetUnit:       '원',
    fixedBudget:      '매달 예산 고정',
    fixedBudgetDesc:  '매달 동일한 예산을 자동 적용합니다.',
    budgetHint:       '예산을 설정하면 차트에서 카테고리별 사용 현황을 확인할 수 있습니다.',
    submit:           '등록하기',
    update:           '수정하기',
    successCreate:    '카테고리가 등록됐습니다.',
    successUpdate:    '카테고리가 수정됐습니다.',
    successDelete:    '카테고리가 삭제됐습니다.',
    deleteBtn:        '카테고리 삭제',
    deleteTitle:      '카테고리 삭제',
    deleteMessage:    '이 카테고리에 속한 내역들을 이동할 카테고리를 선택해주세요.',
    deleteNoCategory: '선택안함 (기타)',
    deleteConfirm:    '삭제',
    addCategory:      '+ 카테고리 추가',
    errNameEmpty:     '카테고리명을 입력해주세요.',
    colorPickerTitle: '색상 선택',
    colorPickerConfirm: '선택',
    emojiPickerTitle: '아이콘 선택',
  },

  transactionEdit: {
    headerCreate:           '내역 추가',
    notifBannerLabel:       '받은 알림',
    categoryRecommended:    '추천 카테고리',
    headerEdit:          '내역 수정',
    installmentLabel:    '할부',
    installmentLumpSum:  '일시불',
    amountLabel:         '금액',
    amountPlaceholder:   '0',
    merchantLabel:       '가맹점',
    merchantPlaceholder: '가맹점명 입력',
    categoryLabel:       '카테고리',
    noCategoryLabel:     '기타 (미분류)',
    categoryPickerEmpty: '카테고리가 없습니다.',
    categoryPickerTitle: '카테고리 선택',
    paymentMethodLabel:        '결제수단',
    paymentMethodPlaceholder:  '결제수단 선택 (선택)',
    paymentMethodPickerTitle:  '결제수단 선택',
    paymentMethodPickerEmpty:  '등록된 결제수단이 없습니다.',
    paymentMethodSectionFixed: '기본',
    paymentMethodSectionCard:  '카드',
    memoLabel:           '메모',
    memoPlaceholder:     '메모 입력 (선택)',
    dateLabel:           '날짜',
    timeLabel:           '시간',
    submit:              '등록하기',
    update:              '수정하기',
    deleteBtn:           '내역 삭제',
    deleteConfirmTitle:  '내역 삭제',
    deleteConfirmMsg:    '이 내역을 삭제하시겠습니까?',
    successCreate:       '내역이 등록됐습니다.',
    successUpdate:       '내역이 수정됐습니다.',
    successDelete:       '내역이 삭제됐습니다.',
    errAmountEmpty:      '금액을 입력해주세요.',
    errAmountZero:       '금액은 1원 이상이어야 합니다.',
    errMerchantEmpty:    '가맹점명을 입력해주세요.',
  },

  timePicker: {
    title:  '시간 선택',
    hour:   '시',
    minute: '분',
    format: (h: number, m: number) => `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`,
  },

  datePicker: {
    weekdays:    ['일', '월', '화', '수', '목', '금', '토'],
    months:      ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    monthFormat:      (year: number, month: number) => `${year}년 ${month}월`,
    yearFormat:       (year: number) => `${year}년`,
    dateFormat:       (year: number, month: number, day: number) => `${year}년 ${month}월 ${day}일`,
    dateWithDowFormat: (year: number, month: number, day: number, dow: string) => `${year}년 ${month}월 ${day}일 (${dow})`,
    allPeriod:        '전체 기간',
  },

  history: {
    header:      '내역',
    empty:       '내역이 없습니다.',
    tabDay:      '일',
    tabMonth:    '월',
    tabYear:     '년',
    today:       '오늘',
    dateFormat:  (y: number, m: number, d: number) => `${y}년 ${m}월 ${d}일`,
    totalAmount: (n: number) => `총 ${n.toLocaleString()}원`,
    noCategory:  '기타',
    groupHourFmt:  (hour: number) => `${hour}시`,
    groupDayFmt:   (day: number, dow: string) => `${day}일 (${dow})`,
    groupMonthFmt: (month: number) => `${month}월`,
    filterPaymentMethod:        '결제수단',
    filterCategory:             '카테고리',
    filterAll:                  '전체',
    filterPaymentMethodSelected: (n: number) => `결제수단 ${n}개`,
    filterCategorySelected:      (n: number) => `카테고리 ${n}개`,
    filterPickerConfirm:         '확인',
    filterPaymentPickerTitle:    '결제수단 필터',
    filterCategoryPickerTitle:   '카테고리 필터',
  },

  stats: {
    header:              '통계',
    tabPeriod:           '날짜',
    tabCategory:         '카테고리',
    tabPaymentMethod:    '결제수단',
    tabDay:              '일',
    tabMonth:            '월',
    tabYear:             '년',
    tabRange:            '기간',
    rangeStart:          '시작일',
    rangeEnd:            '종료일',
    currencyUnit:        '원',
    other:               '기타',
    rangeSeparator:      '~',
    noData:              '해당 기간에 지출 내역이 없습니다.',
    totalExpense:        '총 지출',
    categoryBreakdown:   '카테고리별 지출',
    trendTitle:          '지출 추이',
    top10Title:          '금액 TOP 10',
    selectCategory:      '카테고리를 선택하세요',
    selectPaymentMethod: '결제수단을 선택하세요',
    budgetLabel:         (budget: number) => `예산 ${budget.toLocaleString()}원`,
    budgetPct:           (pct: number) => `${pct}%`,
    budgetOver:          '예산 초과',
    vsPrev:              (period: string, sign: '+' | '-' | '', pct: number) => `전${period} 대비 ${sign}${pct}%`,
    vsPrevSame:          (period: string) => `전${period}과 동일`,
    vsPrevNone:          (period: string) => `전${period} 지출 없음`,
    categoryDiffFmt:     (period: string, sign: '+' | '-', amount: number) => `전${period} 대비 ${sign}${amount.toLocaleString()}원`,
  },

  fixedExpenses: {
    header:          '고정 지출 관리',
    empty:           '등록된 고정 지출이 없습니다.',
    tabList:         '리스트',
    tabCalendar:     '달력',
    dayOfMonthFmt:   (d: number) => `매월 ${d}일`,
    activeLabel:     '자동 등록 중',
    inactiveLabel:   '자동 등록 꺼짐',
  },

  fixedExpenseEdit: {
    headerCreate:           '고정 지출 추가',
    headerEdit:             '고정 지출 수정',
    merchantNameLabel:      '가맹점명',
    merchantNamePlaceholder:'가맹점명 입력',
    amountLabel:            '금액',
    amountPlaceholder:      '금액 입력',
    categoryLabel:          '카테고리',
    categoryPlaceholder:    '카테고리 선택',
    paymentMethodLabel:     '결제수단',
    paymentMethodPlaceholder:'결제수단 선택 (선택)',
    memoLabel:              '메모',
    memoPlaceholder:        '메모 입력 (선택)',
    dayOfMonthLabel:        '매월 지출일',
    dayOfMonthPlaceholder:  '1 ~ 31',
    isActiveLabel:          '매월 자동 등록',
    confirmDisableTitle:    '자동 등록 끄기',
    confirmDisableMsg:      '자동 등록을 끄면 매월 자동으로 내역이 추가되지 않습니다. 계속하시겠습니까?',
    confirmDisableOk:       '끄기',
    confirmDisableCancel:   '취소',
    saveButton:             '저장',
    deleteButton:           '삭제',
    confirmDeleteTitle:     '고정 지출 삭제',
    confirmDeleteMsg:       '삭제하면 복구할 수 없습니다. 삭제하시겠습니까?',
    confirmDeleteOk:        '삭제',
    errMerchantEmpty:       '가맹점명을 입력해 주세요.',
    errAmountEmpty:         '금액을 입력해 주세요.',
    errDayEmpty:            '1~31 사이의 날짜를 입력해 주세요.',
    successCreate:              '고정 지출이 등록되었습니다.',
    successUpdate:              '저장되었습니다.',
    registerThisMonthTitle:     '이번 달 내역 등록',
    registerThisMonthMsg:       (name: string) => `이번 달 ${name} 내역이 없습니다. 지금 등록하시겠습니까?`,
    registerThisMonthOk:        '등록',
    successCreateAndRegister:   '고정 지출 등록 및 이번 달 내역이 추가되었습니다.',
    successUpdateAndRegister:   '저장 완료 및 이번 달 내역이 추가되었습니다.',
  },

  userManagement: {
    header:      '유저 관리',
    searchPlaceholder: '이메일 검색',
    totalCount:  (n: number) => `총 ${n}명`,
    tabActive:   '활성',
    tabSuspended: '정지',
    empty:       '유저가 없습니다.',
    emptySearch: '검색 결과가 없습니다.',
    deviceLabel: (n: number) => `기기 ${n}`,
    suspend:     '사용 정지',
    unsuspend:   '정지 해제',
    confirmSuspendTitle:   '사용 정지',
    confirmSuspendMsg:     '해당 유저를 사용 정지하면 즉시 강제 로그아웃 처리됩니다. 계속하시겠습니까?',
    confirmUnsuspendTitle: '정지 해제',
    confirmUnsuspendMsg:   '해당 유저의 정지를 해제하시겠습니까?',
    noDevice:              '등록된 기기 없음',
  },

  userTabs: {
    home:     '홈',
    history:  '내역',
    stats:    '통계',
    category: '카테고리',
    more:     '전체',
  },
} as const
